version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  main-app:
    build:
      context: ./flask_ci_cd
      dockerfile: Dockerfile
    container_name: flask_ci_cd
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  service-app:
    build:
      context: ./flask_service_ci_cd
      dockerfile: Dockerfile
    container_name: flask_service_ci_cd
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
