apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_ci_cd
  namespace: app-microservices-rabbitmq-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask_ci_cd
  template:
    metadata:
      labels:
        app: flask_ci_cd
    spec:
      containers:
      - name: flask_ci_cd
        image: devsubha/flask_ci_cd:latest
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: flask_ci_cd
  namespace: app-microservices-rabbitmq-ci-cd
spec:
  selector:
    app: flask_ci_cd
  ports:
    - port: 80
      targetPort: 8000