apiVersion: v1
kind: Service
metadata:
  name: flask-ci-cd
  namespace: app-microservices-rabbitmq-ci-cd
spec:
  type: NodePort
  selector:
    app: flask_ci_cd
  ports:
    - port: 80
      targetPort: 8000