apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: app-microservices-rabbitmq-ci-cd
spec:
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management
  selector:
    app: rabbitmq