name: Deploy to Kubernetes

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_MAIN: devsubha/flask_ci_cd
  IMAGE_SERVICE: devsubha/flask_service_ci_cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # # This part is to Test the Main app and Service app
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'

    # - name: Install dependencies for Main app
    #   run: |
    #     pip install -r flask_ci_cd/requirements.txt

    # - name: Run unit tests for Main app
    #   run: |
    #     pytest flask_ci_cd/test_app --maxfail=1 --disable-warnings -q

    # - name: Install dependencies for Service app
    #   run: |
    #     pip install -r flask_service_ci_cd/requirements.txt

    # - name: Run unit tests for Service app
    #   run: |
    #     pytest flask_service_ci_cd/test_app --maxfail=1 --disable-warnings -q

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password:  ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build and push flask_ci_cd
      run: |
        docker build -f ./flask_ci_cd/Dockerfile -t devsubha/flask_ci_cd:latest ./flask_ci_cd
        docker push devsubha/flask_ci_cd:latest

    - name: Build and push flask_service_ci_cd
      run: |
        docker build -f ./flask_service_ci_cd/Dockerfile -t devsubha/flask_service_ci_cd:latest ./flask_service_ci_cd
        docker push devsubha/flask_service_ci_cd:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: v1.29.0
    
    # # Use Cloud Providers like AKS, EKS to create a cluster, create service account and get authentication token K8S_SERVICE_ACCOUNT_TOKEN, KUBERNETES_SERVER_URL is cluster endpoint
    # - name: Authenticate with Kubernetes
    #   run: |
    #     echo "${{ secrets.K8S_SERVICE_ACCOUNT_TOKEN }}" > $HOME/.kube/token
    #     kubectl config set-cluster my-cluster --server=https://<KUBERNETES_SERVER_URL> --insecure-skip-tls-verify=true
    #     kubectl config set-credentials github-actions --token=$(cat $HOME/.kube/token)
    #     kubectl config set-context github-actions-context --cluster=my-cluster --user=github-actions --namespace=app-microservices-rabbitmq-ci/cd
    #     kubectl config use-context github-actions-context

    # # - name: Set up Kubeconfig
    # #   run: |
    # #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
    # #     export KUBECONFIG=$(pwd)/kubeconfig.yaml

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/namespace.yaml
    #     kubectl apply -f k8s/rabbitmq_deployment.yaml
    #     kubectl apply -f k8s/rabbitmq_service.yaml
    #     kubectl apply -f k8s/flask_ci_cd_deployment.yaml
    #     kubectl apply -f k8s/flask_ci_cd_service.yaml
    #     kubectl apply -f k8s/flask_service_ci_cd_deployment.yaml

    # Tests to Run post deployment
    # wait for external IP
    # - name: wait for main-app external ip
    #   run: |
    #     for i in {1..30}; do
    #       EXTERNAL_IP=$(kubectl get svc flask_ci_cd_service -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
    #       if [[ -n "$EXTERNAL_IP" ]]; then
    #         echo "EXTERNAL_IP=$EXTERNAL_IP" >> $GITHUB_ENV
    #         echo "FOUND IP: $EXTERNAL_IP"
    #         break
    #       fi
    #       echo " Waiting for EXTERNAL IP...."
    #       sleep 10
    #     done

    # - name: Save APP URL to .env file
    #   run: |
    #     echo "APP_URL=http://${{ env.EXTERNAL_IP }}" >> flask_ci_cd/.env
    #     cat .env

    # - name: Set up Python for smoke tests
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'

    # - name: Install requests
    #   run: pip install requests

    # - name: Run post-deploy tests
    #   run: python flask_ci_cd/smoke_test.py
    #   env:
    #     APP_URL: http://${{ env.EXTERNAL_IP }}
