name: Deploy to Kubernetes

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_MAIN: devsubha/flask_ci_cd
  IMAGE_SERVICE: devsubha/flask_service_ci_cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password:  ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build and push flask_ci_cd
      run: |
        docker build -f ./flask_ci_cd/Dockerfile -t devsubha/flask_ci_cd:latest ./flask_ci_cd
        docker push devsubha/flask_ci_cd:latest

    - name: Build and push flask_service_ci_cd
      run: |
        docker build -f ./flask_service_ci_cd/Dockerfile -t devsubha/flask_service_ci_cd:latest ./flask_service_ci_cd
        docker push devsubha/flask_service_ci_cd:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: v1.29.0

    # - name: Authenticate with Kubernetes
    #   run: |
    #     echo "${{ secrets.K8S_SERVICE_ACCOUNT_TOKEN }}" > $HOME/.kube/token
    #     kubectl config set-cluster my-cluster --server=https://<KUBERNETES_SERVER_URL> --insecure-skip-tls-verify=true
    #     kubectl config set-credentials github-actions --token=$(cat $HOME/.kube/token)
    #     kubectl config set-context github-actions-context --cluster=my-cluster --user=github-actions --namespace=app-microservices-rabbitmq-ci/cd
    #     kubectl config use-context github-actions-context

    # # - name: Set up Kubeconfig
    # #   run: |
    # #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
    # #     export KUBECONFIG=$(pwd)/kubeconfig.yaml

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/namespace.yaml
    #     kubectl apply -f k8s/rabbitmq_deployment.yaml
    #     kubectl apply -f k8s/flask_ci_cd_deployment.yaml
    #     kubectl apply -f k8s/flask_service_ci_cd_deployment.yaml